### ISSUE TITLE
rebuild module when sources changed

### ISSUE THREAD

**Issue by AtomicFS** [9elements/firmware-action#441]
Right now I have to specify in Taskfile:
```yaml
...
    sources:
      - .. all of the sources ...
    generates:
      - output-coreboot/coreboot.rom
    method: timestamp
...
```

Especially the `sources` part is annoying. I have to basically list all files that are already in the firmware-action JSON config. This should be build-in.

We already have the `generates` functionality covered since #166 . Although we still need to add `--buldozer-mode`.
